# Generated by Django 5.2.8 on 2025-12-05 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedanswer',
            name='answer_title',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='selectedanswer',
            name='correct_answer_title',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='selectedanswer',
            name='question_title',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.test'),
        ),
        migrations.AlterField(
            model_name='selectedanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.answers'),
        ),
        migrations.AlterField(
            model_name='selectedanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.question'),
        ),
        migrations.AlterField(
            model_name='selectedanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_answers', to='core.submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.test'),
        ),
    ]
